version: 0.2

phases:
  install:
    commands:
      - echo "Install phase started"
  pre_build:
    commands:
      - echo "Pre-build phase started"
      - ls -la
  build:
    commands:
      - echo "Build phase started"
      - echo "Showing index.html content"
      - cat index.html
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - index.html
